### ISSUE TITLE
Compiling for es5

### ISSUE THREAD

**Issue by alechirsch** [avoidwork/turtle.io#365]
I am trying to add a feature to this package, but am having trouble with compiling the newest version to be compatible with node v5.

What specific compilation process did you use to compile v6 of turtle.io?

Thanks

**Comment by avoidwork** [comment]
You'd need to go to v5. The current version is not backwards compatible because the router is no longer built in, and also not transpiled to es5 syntax.

Alternatively; fork woodland & add babel, then fork turtle.io & add babel, and have it use your fork of woodland.

**Comment by alechirsch** [comment]
I'm aware that the current version is not compatible, but version 6 of
turtle.io is compatible. I'm currently trying to expose the option called
ciphers from the https package. This is because we want to allow only TLS
v1. 2 and nothing else.

**Comment by avoidwork** [comment]
Hi,

I think this is still a fork situation; one of the core differences between 5.0 and 6.0 was the removal of customization due to the fact that it was already the default state of the instance of `https`.

If you look at https://github.com/avoidwork/turtle.io/blob/5.0/src/turtleio.js#L1564 and compare it to https://github.com/avoidwork/turtle.io/blob/6.0/src/turtleio.js#L647 you'll see the cipher config is completely absent. I think you'd want to customize around line 647 of the 6.0 code base.

**Comment by avoidwork** [comment]
Are you all set? Can I close the issue?

**Comment by alechirsch** [comment]
Yes, you can close this issue. I realized that you used grunt to compile
and runs tests. I branched off of v6. 0 and got ciphers to work.

Thanks for checking in.
